[build]
command = "npm run build"         
publish = "out"                  
functions = "functions"          

[functions]
node_bundler = "esbuild"           

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-functions-install-core" 

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
