[build]
command = "npm install --legacy-peer-deps && npm run build && npx next export"
publish = "out"

# ✅ 불필요한 플러그인 제거
# [[plugins]]
# package = "@netlify/plugin-nextjs"

# ✅ SSR 전용 환경 변수 제거 (충돌 방지)
# [build.environment]
# NEXT_USE_NETLIFY_EDGE = "true"
# NEXT_PRIVATE_TARGET = "server"
